#!/bin/bash

######################################################################
#
#  Copyright (c) 2015 arakasi72 (https://github.com/arakasi72)
#
#  --> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
######################################################################

PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin

rundir=$(dirname $(readlink -f $0))

if [ "$(id -u)" != "0" ]; then
  echo "Must be run as root, directly or with sudo"
  exit 1
fi

if [ $(dpkg-query -W -f='${Status}' git 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
echo "Installing git"
apt-get -yqq install git 2>&1 >> /dev/null
fi

if [ $(dpkg-query -W -f='${Status}' ssh 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
echo "Installing ssh"
apt-get -yqq install ssh 2>&1 >> /dev/null
fi

if [ $(dpkg-query -W -f='${Status}' ca-certificates 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
echo "Installing ca-certificates"
apt-get -yqq install ca-certificates 2>&1 >> /dev/null
fi

echo "Installing rtinst $branch"
cd
rm -fr /etc/rtinst
git clone -q -b master --single-branch https://github.com/pulgalipe/rtinst.git /etc/rtinst
cd /etc/rtinst
ln -sf /etc/rtinst/scripts/* /usr/local/bin
ln -sf /etc/rtinst/rtsetup /usr/local/bin

echo "Installation complete"
echo
echo "You can now run rtinst and the additional supporting scripts"

if [ "$rundir" != "/etc/rtinst" ]; then
    rm -f $rundir/rtsetup
fi
